"""Supported Synaptic Tuner API v1.

Only names exported here are part of the narrow v1 compatibility surface.
Internal ``tuner`` and ``shared`` modules are not implicitly public APIs.
"""

from .capabilities import CapabilityDescriptor
from .context import PathRef, ProjectContext
from .events import EventEnvelope, ResultEnvelope
from .execution import (
    ArtifactRef,
    ArtifactState,
    AuthorizationRequirement,
    ErrorCode,
    ExecutionError,
    ExecutionGrant,
    RunRef,
    RunState,
    RunStatus,
)
from .host import APIHost,Clock,EvidenceAuthenticator,EvidenceReplayStore,GitRemoteReader,GrantProvider,HostPorts,LifecycleRepository,ModalDeploymentReader,SecretProvider
from .plugins import PluginBinding, PluginContext
from .runs import (
    ArtifactPage,
    ArtifactsRequest,
    CancelResult,
    LogEntry,
    LogPage,
    ReconcileRequest,
    RunCancelRequest,
    RunListRequest,
    RunLogsRequest,
    RunPage,
    RunVerification,
    RunsAPI,
    RunsOperations,
    VerifyRequest,
)
from .secrets import SecretRef
from .sources import (
    AuthenticatedSourceEvidenceV1,
    ExecutionSourceV1,
    LocalSourceInspectionPort,
    PushedSourceVerificationPort,
    SourceLock,
)
from .training import (
    ArtifactPolicy,
    CanonicalDocument,
    ResolvedTrainingRequest,
    ResourceSpec,
    RuntimeSpec,
    TrainingAPI,
    TrainingOperations,
    TrainingOutcome,
    TrainingPlan,
    TrainingPreflight,
    TrainingRequest,
    TrainingSubmission,
)

__all__ = [
    "APIHost",
    "ArtifactPage",
    "ArtifactPolicy",
    "ArtifactRef",
    "ArtifactState",
    "ArtifactsRequest",
    "AuthorizationRequirement",
    "CapabilityDescriptor",
    "CancelResult",
    "CanonicalDocument",
    "ErrorCode",
    "EventEnvelope",
    "ExecutionError",
    "ExecutionGrant",
    "EvidenceAuthenticator",
    "EvidenceReplayStore",
    "Clock",
    "GitRemoteReader",
    "GrantProvider",
    "HostPorts",
    "LifecycleRepository",
    "ModalDeploymentReader",
    "LogEntry",
    "LogPage",
    "PathRef",
    "PluginBinding",
    "PluginContext",
    "ProjectContext",
    "ReconcileRequest",
    "ResolvedTrainingRequest",
    "ResultEnvelope",
    "ResourceSpec",
    "RunCancelRequest",
    "RunListRequest",
    "RunLogsRequest",
    "RunPage",
    "RunRef",
    "RunState",
    "RunStatus",
    "RunVerification",
    "RunsAPI",
    "RunsOperations",
    "RuntimeSpec",
    "SecretRef",
    "SecretProvider",
    "SourceLock",
    "AuthenticatedSourceEvidenceV1",
    "ExecutionSourceV1",
    "LocalSourceInspectionPort",
    "PushedSourceVerificationPort",
    "TrainingAPI",
    "TrainingOperations",
    "TrainingOutcome",
    "TrainingPlan",
    "TrainingPreflight",
    "TrainingRequest",
    "TrainingSubmission",
    "VerifyRequest",
]
