"""Supported Synaptic Tuner API v1.

Only names exported here are part of the narrow v1 compatibility surface.
Internal ``tuner`` and ``shared`` modules are not implicitly public APIs.
"""

from .capabilities import CapabilityDescriptor
from .artifacts import (
    ArtifactPublicationReceipt,
    ArtifactPublisher,
    PublishedArtifact,
    VerifiedArtifactDescriptor,
    VerifiedArtifactSource,
)
from .context import PathRef, ProjectContext
from .events import EventEnvelope, ResultEnvelope
from .execution import (
    ArtifactRef,
    ArtifactState,
    AuthorizationRequirement,
    ErrorCode,
    ExecutionError,
    ExecutionGrant,
    RunRef,
    RunState,
    RunStatus,
)
from .host import APIHost,Clock,EvidenceAuthenticator,EvidenceReplayStore,GitRemoteReader,GrantProvider,HostPorts,LifecycleRepository,ModalDeploymentReader,SecretProvider
from .plugins import PluginBinding, PluginContext
from .persistence import (
    AttemptAdmission,
    AttemptDisposition,
    AuthorizationMismatch,
    EffectCollision,
    EffectDisposition,
    EffectIdentity,
    EffectKind,
    EffectObservation,
    EffectRecord,
    EffectState,
    EvidenceReplayRepository,
    EventCode,
    ExecutionScope,
    GrantBinding,
    InvalidTransition,
    LifecycleEvent,
    LifecyclePhase,
    LifecycleRecord,
    LifecycleRunPage,
    MessageCode,
    OperationBindingV1,
    RevisionConflict,
    ReplayDisposition,
    RunAlreadyExists,
    RunNotFound,
    VerificationStatus,
    apply_lifecycle_event,
)
from .runs import (
    ArtifactPage,
    ArtifactsRequest,
    CancelResult,
    LogEntry,
    LogPage,
    ReconcileRequest,
    RunCancelRequest,
    RunListRequest,
    RunLogsRequest,
    RunPage,
    RunVerification,
    RunsAPI,
    RunsOperations,
    VerifyRequest,
)
from .secrets import SecretRef
from .sources import (
    AuthenticatedSourceEvidenceV1,
    ExecutionSourceV1,
    GitCliLocalSourceInspector,
    LocalSourceInspectionPort,
    PushedSourceVerificationPort,
    SourceLock,
)
from .training import (
    ArtifactPolicy,
    CanonicalDocument,
    ResolvedTrainingComponents,
    ResolvedTrainingRequest,
    ResourceSpec,
    RuntimeSpec,
    TrainingAPI,
    TrainingOperations,
    TrainingOutcome,
    TrainingPlan,
    TrainingPreflight,
    TrainingRequest,
    TrainingRequestResolver,
    TrainingResolutionError,
    TrainingSubmission,
)

__all__ = [
    "APIHost",
    "AttemptAdmission",
    "AttemptDisposition",
    "ArtifactPage",
    "ArtifactPublicationReceipt",
    "ArtifactPublisher",
    "ArtifactPolicy",
    "ArtifactRef",
    "ArtifactState",
    "ArtifactsRequest",
    "AuthorizationRequirement",
    "AuthorizationMismatch",
    "CapabilityDescriptor",
    "CancelResult",
    "CanonicalDocument",
    "ErrorCode",
    "EffectCollision",
    "EffectDisposition",
    "EffectIdentity",
    "EffectKind",
    "EffectObservation",
    "EffectRecord",
    "EffectState",
    "EvidenceReplayRepository",
    "EventEnvelope",
    "ExecutionError",
    "ExecutionGrant",
    "ExecutionScope",
    "EvidenceAuthenticator",
    "EvidenceReplayStore",
    "Clock",
    "GitRemoteReader",
    "GitCliLocalSourceInspector",
    "GrantProvider",
    "GrantBinding",
    "HostPorts",
    "LifecycleRepository",
    "LifecycleEvent",
    "LifecyclePhase",
    "LifecycleRecord",
    "LifecycleRunPage",
    "ModalDeploymentReader",
    "MessageCode",
    "LogEntry",
    "LogPage",
    "PathRef",
    "PluginBinding",
    "PluginContext",
    "PublishedArtifact",
    "OperationBindingV1",
    "ProjectContext",
    "ReconcileRequest",
    "ResolvedTrainingRequest",
    "ResolvedTrainingComponents",
    "ResultEnvelope",
    "ResourceSpec",
    "RunCancelRequest",
    "RunListRequest",
    "RunLogsRequest",
    "RunPage",
    "RunRef",
    "RunAlreadyExists",
    "RunNotFound",
    "RunState",
    "RunStatus",
    "RunVerification",
    "RunsAPI",
    "RunsOperations",
    "RuntimeSpec",
    "ReplayDisposition",
    "RevisionConflict",
    "SecretRef",
    "SecretProvider",
    "SourceLock",
    "AuthenticatedSourceEvidenceV1",
    "ExecutionSourceV1",
    "LocalSourceInspectionPort",
    "PushedSourceVerificationPort",
    "TrainingAPI",
    "TrainingOperations",
    "TrainingOutcome",
    "TrainingPlan",
    "TrainingPreflight",
    "TrainingRequest",
    "TrainingRequestResolver",
    "TrainingResolutionError",
    "TrainingSubmission",
    "VerificationStatus",
    "VerifiedArtifactDescriptor",
    "VerifiedArtifactSource",
    "InvalidTransition",
    "apply_lifecycle_event",
    "VerifyRequest",
]
