#!/usr/bin/env python3
"""Quantitative synthesis over evidence/effects.csv.

Because this literature almost never reports variances (see raw reports:
0 of 12 calibration papers report error bars), formal random-effects pooling
is impossible for most claim families. We therefore run, per claim family:

1. Vote counting with an exact two-sided binomial sign test across
   independent studies (does the direction of effect replicate?).
2. Descriptive normalization: relative % change where a baseline exists,
   reported as median [min, max] across studies.
3. A forest-style dot plot of relative effects (figures/forest.png).

Where variance IS reported (SycEval CI; JMIR p-values) it is carried in the
table and noted. This is the honest hybrid promised in the methods section.

Run: python3 synthesize.py  (writes synthesis-summary.md + figures/forest.png)
"""

from pathlib import Path

import pandas as pd
from scipy.stats import binomtest

HERE = Path(__file__).resolve().parent
EV = HERE.parent / "evidence" / "effects.csv"
OUT = HERE / "synthesis-summary.md"
FIG = HERE / "figures" / "forest.png"

# Claim families: (name, hypothesis statement, row filter, support test)
# support test: given a row, return True if it supports the hypothesis,
# False if it contradicts, None if not informative.


def effect_sign(row):
    """Signed effect: positive = metric moved up from baseline to treatment."""
    if pd.notna(row.rel_change_pct):
        return float(row.rel_change_pct)
    if pd.notna(row.delta):
        return float(row.delta)
    return None


def supports_degradation(row):
    """Alignment/tuning degrades a lower-is-better metric (or lowers a
    higher-is-better one)."""
    e = effect_sign(row)
    if e is None or e == 0:
        return None
    worse = (row.direction == "lower" and e > 0) or (row.direction == "higher" and e < 0)
    return worse


def supports_improvement(row):
    e = effect_sign(row)
    if e is None or e == 0:
        return None
    better = (row.direction == "lower" and e < 0) or (row.direction == "higher" and e > 0)
    return better


FAMILIES = [
    (
        "C1: instruction-tuning/RLHF degrades token-probability calibration",
        lambda d: d[(d.area == "calibration") & d.comparison.isin(["pretrain_vs_rlhf", "base_vs_instruct"]) & (d.metric.str.contains("ECE", case=False))],
        supports_degradation,
    ),
    (
        "C2: preference-based methods beat SFT on abstention/truthfulness quality",
        lambda d: d[d.comparison.isin(["sft_vs_pref", "sft_vs_dpo", "sft_vs_kto"]) & (d.metric.str.contains("truthful|reasoning|TruthfulQA", case=False))],
        supports_improvement,
    ),
    (
        "C3: preference optimization reduces SFT abstention over-refusal",
        lambda d: d[(d.comparison == "sft_vs_pref") & (d.metric.str.contains("over-refusal", case=False))],
        supports_improvement,
    ),
    (
        "C4: scale alone does not produce epistemic humility (sycophancy/self-knowledge)",
        lambda d: d[d.comparison.isin(["scale", "scale_inverse", "scale_and_rlhf", "scale_and_tuning"]) & d.area.isin(["sycophancy", "hallucination", "knowledge-boundary"])],
        supports_degradation,  # support = humility metric worsens or stays below human with scale
    ),
    (
        "C5: targeted training interventions improve humility metrics",
        lambda d: d[d.comparison.isin(["refusal_aware_sft", "honesty_sft", "dpo_calibration", "dpo_factuality", "factuality_aware_alignment", "synthetic_data_intervention", "sft_intervention", "rlhf_variant", "posthoc_fix", "multi_llm_abstention"])],
        supports_improvement,
    ),
]


def main() -> None:
    d = pd.read_csv(EV)
    lines = [
        "# Synthesis summary (auto-generated by synthesize.py)",
        "",
        f"Evidence rows: {len(d)} from {d.study.nunique()} studies. "
        f"Rows verified against primary sources: {int(d.verified.sum())} "
        f"({d[d.verified].study.nunique()} studies); the rest are flagged "
        "`verified=false` pending PDF access (see HANDOFF.md).",
        "",
        "Method: vote counting + exact binomial sign test per claim family; "
        "descriptive normalization (relative % change) where baselines exist. "
        "Formal pooling deferred — variances are unreported in this literature.",
        "",
    ]

    plot_rows = []
    for name, selector, judge in FAMILIES:
        sub = selector(d).copy()
        votes = {True: [], False: []}
        for _, row in sub.iterrows():
            v = judge(row)
            if v is not None:
                votes[v].append(row.study)
        n_sup = len(set(votes[True]))
        n_con = len(set(votes[False]))
        n = n_sup + n_con
        p = binomtest(n_sup, n, 0.5).pvalue if n else float("nan")
        rels = sub.rel_change_pct.dropna()
        rel_txt = (
            f"median |rel change| {rels.abs().median():.1f}% "
            f"[range {rels.min():.1f}%, {rels.max():.1f}%]"
            if len(rels)
            else "no normalizable effects"
        )
        lines += [
            f"## {name}",
            "",
            f"- Studies supporting: **{n_sup}** | contradicting: **{n_con}** "
            f"| sign-test p = {p:.4f}" if n else "- no informative rows",
            f"- Effect sizes: {rel_txt}",
            f"- Rows: {', '.join(sorted(set(sub.study)))}",
            "",
        ]
        for _, row in sub.iterrows():
            e = effect_sign(row)
            if e is not None and pd.notna(row.rel_change_pct):
                plot_rows.append((name.split(":")[0], f"{row.paper} ({row.metric})", float(row.rel_change_pct), bool(row.verified)))

    lines += [
        "## Variance-aware rows (the only ones in the corpus)",
        "",
    ]
    var_rows = d[d.variance_reported == True]  # noqa: E712
    for _, row in var_rows.iterrows():
        lines.append(f"- {row.paper}: {row.metric} = {row.treatment} ({row.notes})")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.name}")

    # forest-style plot
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if plot_rows:
        fig, ax = plt.subplots(figsize=(9, 0.34 * len(plot_rows) + 2))
        ys = range(len(plot_rows))
        colors = ["#2a7" if v else "#c66" for *_, v in plot_rows]
        ax.scatter([r[2] for r in plot_rows], list(ys), c=colors, s=40, zorder=3)
        ax.axvline(0, color="#888", lw=1)
        ax.set_yticks(list(ys))
        ax.set_yticklabels([f"{fam} | {label}" for fam, label, *_ in plot_rows], fontsize=7)
        ax.set_xlabel("relative change from baseline (%)  —  green = verified against primary source")
        ax.set_title("Normalized effects across the epistemic-humility training literature")
        ax.invert_yaxis()
        fig.tight_layout()
        FIG.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(FIG, dpi=160)
        print(f"wrote figures/{FIG.name}")


if __name__ == "__main__":
    main()
